import {
    Card,
    CardContent,
    CardDescription,
    CardHeader,
    CardTitle,
  } from '@/components/ui/card';

export default function DisclaimerPage() {
  return (
    <div className="flex flex-col gap-6 max-w-4xl mx-auto">
      <div className="space-y-1">
        <h1 className="text-2xl font-bold tracking-tight">Disclaimer</h1>
        <p className="text-muted-foreground">
          Important information about the use of Market Pulse AI.
        </p>
      </div>
      <Card>
        <CardHeader>
          <CardTitle>Statistical Indicators, Not Investment Advice</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4 text-muted-foreground">
          <p>
            Market Pulse AI is a financial data analytics and intelligence tool. The information provided, including risk scores, anomaly indicators, summaries, and explanations, is generated by automated systems and artificial intelligence. This information is for informational purposes only and should not be construed as investment advice, financial guidance, or a recommendation to buy, sell, or hold any security.
          </p>
          <p>
            The platform's outputs are based on statistical analysis of market data and publicly available information. They are intended to serve as "Statistical Anomaly Indicators" to highlight unusual market movements relative to historical patterns. These are not accusations of wrongdoing, confirmations of news, or predictions of future price movements.
          </p>
          <p>
            All investment decisions should be made with the consultation of a qualified financial advisor. Market Pulse AI and its affiliates are not liable for any financial losses or decisions made based on the information provided on this platform.
          </p>
          <p>
            The app must not be used for any unlawful purpose, and we do not endorse or engage in the blacklisting of any company. Our goal is to provide purely reaction-based market intelligence.
          </p>
        </CardContent>
      </Card>
    </div>
  );
}
