import { announcementSummaryAndEntities } from "@/ai/flows/announcement-summary-and-entities";
import { mlRiskScoreExplanation } from "@/ai/flows/ml-risk-score-explanation-flow";
import { Announcement } from "@/lib/types";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { AlertCircle, TrendingDown, TrendingUp, Landmark, Building, User, Building2, Globe } from "lucide-react";

function getRiskBadgeVariant(score: number): "default" | "destructive" | "secondary" {
    if (score > 60) return "destructive";
    if (score > 30) return "secondary";
    return "default";
}

const entityIcons: { [key: string]: React.ElementType } = {
    'Company': Building,
    'Subsidiary': Building2,
    'Counterparty': Landmark,
    'Financial Backer': Landmark,
    'Bank': Landmark,
    'Individual': User,
    'default': Globe,
};

type AnnouncementIntelligenceProps = {
    announcement: Announcement;
};

export async function AnnouncementIntelligence({ announcement }: AnnouncementIntelligenceProps) {
    const [summary, riskExplanation] = await Promise.all([
        announcementSummaryAndEntities({ fullText: announcement.fullText }),
        mlRiskScoreExplanation({
            symbol: announcement.symbol,
            timestamp: announcement.timestamp,
            risk_score: announcement.riskScore,
            abnormal_return: announcement.abnormalReturn,
            volume_spike_ratio: announcement.volumeSpikeRatio,
        }),
    ]);

    const marketReactionMetrics = [
        { label: "Price Change", value: `${announcement.abnormalReturn}%`, icon: announcement.abnormalReturn > 0 ? TrendingUp : TrendingDown, color: announcement.abnormalReturn > 0 ? "text-green-500" : "text-red-500" },
        { label: "Volume Spike", value: `${announcement.volumeSpikeRatio}x`, icon: AlertCircle, color: announcement.volumeSpikeRatio > 2 ? "text-orange-500" : "text-muted-foreground" },
        { label: "Risk Score", value: announcement.riskScore, icon: AlertCircle, color: announcement.riskScore > 60 ? "text-red-500" : (announcement.riskScore > 30 ? "text-orange-500" : "text-green-500") },
    ];

    return (
        <Card>
            <CardHeader>
                <div className="flex justify-between items-start">
                    <div>
                        <CardTitle>AI-Powered Announcement Analysis</CardTitle>
                        <CardDescription>Generated by Market Pulse AI</CardDescription>
                    </div>
                    <Badge variant={getRiskBadgeVariant(announcement.riskScore)}>
                        {riskExplanation.category}
                    </Badge>
                </div>
            </CardHeader>
            <CardContent className="space-y-6">
                <div>
                    <h3 className="font-semibold text-lg font-headline mb-2">AI Summary</h3>
                    <p className="text-sm text-muted-foreground">{summary.summary}</p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <div>
                        <h3 className="font-semibold text-lg font-headline mb-2">Market Reaction</h3>
                        <div className="space-y-3">
                            {marketReactionMetrics.map(metric => (
                                <div key={metric.label} className="flex items-center justify-between text-sm">
                                    <div className="flex items-center gap-2">
                                        <metric.icon className={`h-4 w-4 ${metric.color}`} />
                                        <span className="text-muted-foreground">{metric.label}</span>
                                    </div>
                                    <span className={`font-semibold ${metric.color}`}>{metric.value}</span>
                                </div>
                            ))}
                        </div>
                    </div>
                    <div>
                        <h3 className="font-semibold text-lg font-headline mb-2">Extracted Entities</h3>
                        <div className="space-y-3">
                            {summary.extractedEntities.map(entity => {
                                const Icon = entityIcons[entity.type] || entityIcons.default;
                                return (
                                <div key={entity.name} className="flex items-center justify-between text-sm">
                                    <div className="flex items-center gap-2">
                                        <Icon className="h-4 w-4 text-muted-foreground" />
                                        <span className="font-semibold">{entity.name}</span>
                                    </div>
                                    <Badge variant="outline">{entity.type}</Badge>
                                </div>
                                )
                            })}
                        </div>
                    </div>
                </div>

                <div>
                    <h3 className="font-semibold text-lg font-headline mb-2">Risk Explanation</h3>
                    <p className="text-sm text-muted-foreground">{riskExplanation.explanation}</p>
                </div>
            </CardContent>
        </Card>
    );
}
